package com.simpletask.e_personal

import com.simpletask.e_personal.Exercicio as Exercicio1

data class Exercicio(val nome: String, val series: Int, val repeticoes: String)

class TreinoPeito {
    companion object {
        fun treinoEmagrecimento(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Supino Inclinado com Barra", 3, "12-15"),
                Exercicio1("Supino Declinado com Halteres", 3, "12-15"),
                Exercicio1("Crucifixo com Cabos", 3, "12-15"),
                Exercicio1("Pull-Over com Halteres", 3, "12-15"),
                Exercicio1("Flexão de Braços (joelhos apoiados, se necessário)", 3, "15-20"),
                Exercicio1("Supino Reto com Barra", 3, "12-15"),
                Exercicio1("Supino Declinado com Barra", 3, "12-15"),
                Exercicio1("Mergulhos em Paralelas", 3, "12-15"),
                Exercicio1("Flexão de Braços com Pernas Elevadas", 3, "15-20"),
                Exercicio1("Aperto de Mão no Pulley", 3, "12-15"),
                Exercicio1("Supino com Pegada Fechada", 3, "12-15"),
                Exercicio1("Flyes com Halteres", 3, "12-15"),
                Exercicio1("Supino Inclinado na Máquina", 3, "12-15"),
                Exercicio1("Push-Up Plyo (flexões explosivas com salto)", 3, "12-15"),
                Exercicio1("Supino Declinado na Máquina", 3, "12-15"),
                Exercicio1("Supino com Pegada Larga", 3, "12-15"),
                Exercicio1("Cross-Over com Cabos", 3, "12-15"),
                Exercicio1("Supino na Máquina Smith", 3, "12-15"),
                Exercicio1("Flexões Declinadas", 3, "15-20"),
                Exercicio1("Supino com Pegada Neutra", 3, "12-15"),
                Exercicio1("Pull-Over na Máquina", 3, "12-15"),
                Exercicio1("Flexões com os Pés Elevados", 3, "15-20"),
                Exercicio1("Mergulhos com Bola Suíça", 3, "12-15"),
                Exercicio1("Supino Reto com Halteres", 3, "12-15"),
                Exercicio1("Supino Inclinado com Barra", 3, "12-15"),
                Exercicio1("Crucifixo na Máquina", 3, "12-15"),
                Exercicio1("Push-Ups com Deslize", 3, "15-20"),
                Exercicio1("Aperto de Mão na Máquina", 3, "12-15"),
                Exercicio1("Supino com Corda", 3, "12-15"),
                Exercicio1("Flexões Explosivas", 3, "12-15"),
                Exercicio1("Flyes Inclinados com Halteres", 3, "12-15"),
                Exercicio1("Mergulhos em Barras Paralelas", 3, "12-15"),
                Exercicio1("Supino na Máquina Hammer Strength", 3, "12-15"),
                Exercicio1("Flexões com Toque no Ombro", 3, "15-20"),
                Exercicio1("Crucifixo Declinado na Máquina", 3, "12-15"),
                Exercicio1("Supino Inclinado com Halteres Leves", 3, "15-20"),
                Exercicio1("Supino Declinado com Halteres", 3, "12-15"),
                Exercicio1("Push-Ups de Tríceps", 3, "12-15"),
                Exercicio1("Flexões com Rotação (alternar entre as mãos)", 3, "12-15"),
                Exercicio1("Mergulhos no Banco (uso de bancos inclinados)", 3, "12-15"),
                Exercicio1("Flexões com Pernas no Banco", 3, "15-20"),
            )
        }

        fun treinoHipertrofia(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Supino Reto com Barra", 4, "8-10"),
                Exercicio1("Supino Inclinado com Halteres", 4, "8-10"),
                Exercicio1("Supino Declinado com Barra", 4, "8-10"),
                Exercicio1("Crucifixo Inclinado com Halteres", 4, "10-12"),
                Exercicio1("Mergulhos em Paralelas", 4, "10-12"),
                Exercicio1("Supino Inclinado na Máquina", 4, "10-12"),
                Exercicio1("Supino Reto na Máquina Smith", 4, "8-10"),
                Exercicio1("Crucifixo na Máquina", 4, "10-12"),
                Exercicio1("Flyes com Cabos", 4, "10-12"),
                Exercicio1("Supino com Pegada Fechada", 4, "10-12"),
                Exercicio1("Supino com Pegada Ampla", 4, "8-10"),
                Exercicio1("Flexões Ponderadas (com peso extra)", 4, "8-10"),
                Exercicio1("Peck Deck (máquina de peitoral)", 4, "10-12"),
                Exercicio1("Supino Declinado na Máquina", 4, "10-12"),
                Exercicio1("Aperto de Mão no Pulley Alto", 4, "10-12"),
                Exercicio1("Cross-Over com Corda", 4, "12-15"),
                Exercicio1("Supino com Pegada Neutra na Máquina Smith", 4, "10-12"),
                Exercicio1("Flexões com Parada (parar no meio do movimento)", 4, "10-12"),
                Exercicio1("Mergulhos no Banco (uso de bancos inclinados)", 4, "10-12"),
                Exercicio1("Supino na Máquina Hammer Strength", 4, "8-10"),
                Exercicio1("Flexões em Barras Paralelas", 4, "10-12"),
                Exercicio1("Flexões Declinadas", 4, "12-15"),
                Exercicio1("Flyes Declinados com Halteres", 4, "10-12"),
                Exercicio1("Supino Inclinado com Halteres Leves", 4, "12-15"),
                Exercicio1("Pullovers na Máquina", 4, "10-12"),
                Exercicio1("Flexões com Peso Corporal", 4, "12-15"),
                Exercicio1("Flyes Pec-Deck (máquina de voar)", 4, "12-15"),
                Exercicio1("Supino Declinado com Halteres Leves", 4, "12-15"),
                Exercicio1("Push-Ups na Bola Suíça", 4, "10-12"),
                Exercicio1("Supino com Pegada Larga na Máquina Smith", 4, "10-12"),
                Exercicio1("Mergulhos em Bancos Paralelos com Peso", 4, "10-12"),
                Exercicio1("Pullovers com Barra", 4, "10-12"),
                Exercicio1("Flyes com Halteres Declinados", 4, "10-12"),
                Exercicio1("Supino Inclinado com Halteres Pesados", 4, "8-10"),
                Exercicio1("Flexões no Solo", 4, "12-15"),
                Exercicio1("Supino Reto com Halteres Pesados", 4, "8-10"),
                Exercicio1("Crucifixo na Máquina Cross-Over", 4, "10-12"),
                Exercicio1("Flexões com os Pés Elevados", 4, "12-15"),
                Exercicio1("Flexões Declinadas com Peso Corporal", 4, "12-15"),
                Exercicio1("Supino com Pegada Fechada na Máquina", 4, "10-12"),
                Exercicio1("Supino com Corda na Polia Alta", 4, "10-12"),
            )
        }

        fun treinoDefinicao(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Supino Declinado com Barra (peso moderado)", 4, "10-12"),
                Exercicio1("Supino Inclinado com Halteres", 4, "10-12"),
                Exercicio1("Crucifixo com Cabos (contração muscular)", 4, "12-15"),
                Exercicio1("Flexões Explosivas", 4, "12-15"),
                Exercicio1("Pulldown na Máquina (parte superior do peito)", 4, "12-15"),
                Exercicio1("Supino Declinado com Halteres (peso moderado)", 4, "10-12"),
                Exercicio1("Cross-Over com Cabos (variação de ângulo)", 4, "12-15"),
                Exercicio1("Flexões em Diamante (mãos próximas)", 4, "12-15"),
                Exercicio1("Flyes com Halteres (peso moderado)", 4, "10-12"),
                Exercicio1("Mergulhos em Paralelas (contração muscular)", 4, "12-15"),
                Exercicio1("Supino com Pegada Neutra na Máquina", 4, "10-12"),
                Exercicio1("Flexões na Bola de Estabilidade (trabalho do core)", 4, "12-15"),
                Exercicio1("Supino na Máquina Smith (peso moderado)", 4, "10-12"),
                Exercicio1("Flexões com Rotação (alternar entre as mãos)", 4, "12-15"),
                Exercicio1("Flexões Declinadas (peso corporal ou com peso extra)", 4, "12-15"),
                Exercicio1("Supino Declinado na Máquina (peso moderado)", 4, "10-12"),
                Exercicio1("Flyes Declinados na Máquina", 4, "12-15"),
                Exercicio1("Supino na Máquina Hammer Strength (peso moderado)", 4, "10-12"),
                Exercicio1("Cross-Over com Corda (variação de amplitude)", 4, "12-15"),
                Exercicio1("Flexões Pliométricas (saltos explosivos)", 4, "12-15"),
                Exercicio1("Supino Inclinado com Barra (peso moderado)", 4, "10-12"),
                Exercicio1("Supino Declinado com Barra (peso moderado)", 4, "10-12"),
                Exercicio1("Crucifixo com Cabos (contração muscular)", 4, "12-15"),
                Exercicio1("Flexões Explosivas", 4, "12-15"),
                Exercicio1("Pulldown na Máquina (parte superior do peito)", 4, "12-15"),
                Exercicio1("Supino Declinado com Halteres (peso moderado)", 4, "10-12"),
                Exercicio1("Cross-Over com Cabos (variação de ângulo)", 4, "12-15"),
                Exercicio1("Flexões em Diamante (mãos próximas)", 4, "12-15"),
                Exercicio1("Flyes com Halteres (peso moderado)", 4, "10-12"),
                Exercicio1("Mergulhos em Paralelas (contração muscular)", 4, "12-15"),
                Exercicio1("Supino com Pegada Neutra na Máquina", 4, "10-12"),
                Exercicio1("Flexões na Bola de Estabilidade (trabalho do core)", 4, "12-15"),
                Exercicio1("Supino na Máquina Smith (peso moderado)", 4, "10-12"),
                Exercicio1("Flexões com Rotação (alternar entre as mãos)", 4, "12-15"),
                Exercicio1("Flexões Declinadas (peso corporal ou com peso extra)", 4, "12-15"),
                Exercicio1("Supino Declinado na Máquina (peso moderado)", 4, "10-12"),
                Exercicio1("Flyes Declinados na Máquina", 4, "12-15"),
                Exercicio1("Supino na Máquina Hammer Strength (peso moderado)", 4, "10-12"),
                Exercicio1("Cross-Over com Corda (variação de amplitude)", 4, "12-15"),
                Exercicio1("Flexões Pliométricas (saltos explosivos)", 4, "12-15")
            )
        }
    }

}

class TreinoCostas {
    companion object {
        fun treinoHipertrofiaCostas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Puxada na Polia Alta (pegada larga)", 4, "8-10"),
                Exercicio1("Levantamento Terra", 4, "6-8"),
                Exercicio1("Barra Fixa (pronada)", 4, "8-10"),
                Exercicio1("Remada Curvada", 4, "8-10"),
                Exercicio1("Puxada na Polia Baixa (pegada supinada)", 4, "8-10"),
                Exercicio1("Pull-Ups (pegada larga)", 4, "8-10"),
                Exercicio1("Remada Cavalinho", 4, "10-12"),
                Exercicio1("Pulldown com Barra (pegada aberta)", 4, "8-10"),
                Exercicio1("Mergulho em Paralelas", 4, "8-10"),
                Exercicio1("Remada Unilateral com Halteres", 4, "10-12"),
                Exercicio1("Pull-Ups (pegada supinada)", 4, "8-10"),
                Exercicio1("Puxada no Cabo com Pegada Neutra", 4, "8-10"),
                Exercicio1("Bent Over Rows com Barra", 4, "8-10"),
                Exercicio1("Pulldown na Máquina", 4, "8-10"),
                Exercicio1("Remada T", 4, "10-12"),
                Exercicio1("Puxada Alta com Corda", 4, "10-12"),
                Exercicio1("Deadlift Romano", 4, "6-8"),
                Exercicio1("Pull-Ups com Peso Extra", 4, "6-8"),
                Exercicio1("Puxada Fechada na Polia Alta", 4, "8-10"),
                Exercicio1("Remada Baixa com Barra T", 4, "8-10"),
                Exercicio1("Puxada na Máquina Hammer Strength", 4, "8-10"),
                Exercicio1("Levantamento Terra com Barra Hexagonal", 4, "6-8"),
                Exercicio1("Pull-Ups com Pegada Neutra", 4, "8-10"),
                Exercicio1("Pulldown na Máquina (pegada supinada)", 4, "10-12"),
                Exercicio1("Mergulho em Paralelas com Peso Extra", 4, "6-8"),
                Exercicio1("Remada Unilateral com Barra T", 4, "8-10"),
                Exercicio1("Puxada com Triângulo na Polia Alta", 4, "8-10"),
                Exercicio1("T-Bar Row", 4, "8-10"),
                Exercicio1("Pulldown com Corda", 4, "10-12"),
                Exercicio1("Mergulho em Paralelas (pegada larga)", 4, "8-10"),
                Exercicio1("Remada na Máquina", 4, "8-10"),
                Exercicio1("Puxada Horizontal na Máquina", 4, "8-10"),
                Exercicio1("Deadlift com Pegada Alternada", 4, "6-8"),
                Exercicio1("Pull-Ups (pegada neutra) com Peso Extra", 4, "6-8"),
                Exercicio1("Puxada no Cabo (pegada supinada)", 4, "8-10"),
                Exercicio1("Remada Sentada", 4, "8-10"),
                Exercicio1("Pulldown na Máquina (pegada larga)", 4, "10-12"),
                Exercicio1("Pull-Ups (pegada mista)", 4, "8-10"),
                Exercicio1("Puxada no Cabo com Pegada Fechada", 4, "8-10"),
                Exercicio1("Deadlift Sumô", 4, "6-8"),
                Exercicio1("Pull-Ups (pegada larga) com Pegada Neutra", 4, "8-10")
            )
        }

        fun treinoEmagrecimentoCostas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Puxada na Polia Alta (pegada larga)", 4, "12-15"),
                Exercicio1("Levantamento Terra", 4, "10-12"),
                Exercicio1("Barra Fixa (pronada)", 4, "12-15"),
                Exercicio1("Remada Curvada", 4, "12-15"),
                Exercicio1("Puxada na Polia Baixa (pegada supinada)", 4, "12-15"),
                Exercicio1("Pull-Ups (pegada larga)", 4, "12-15"),
                Exercicio1("Remada Cavalinho", 4, "12-15"),
                Exercicio1("Pulldown com Barra (pegada aberta)", 4, "12-15"),
                Exercicio1("Mergulho em Paralelas", 4, "12-15"),
                Exercicio1("Remada Unilateral com Halteres", 4, "12-15"),
                Exercicio1("Pull-Ups (pegada supinada)", 4, "12-15"),
                Exercicio1("Puxada no Cabo com Pegada Neutra", 4, "12-15"),
                Exercicio1("Bent Over Rows com Barra", 4, "12-15"),
                Exercicio1("Pulldown na Máquina", 4, "12-15"),
                Exercicio1("Remada T", 4, "12-15"),
                Exercicio1("Puxada Alta com Corda", 4, "12-15"),
                Exercicio1("Deadlift Romano", 4, "10-12"),
                Exercicio1("Pull-Ups com Peso Extra", 4, "10-12"),
                Exercicio1("Puxada Fechada na Polia Alta", 4, "12-15"),
                Exercicio1("Remada Baixa com Barra T", 4, "12-15"),
                Exercicio1("Puxada na Máquina Hammer Strength", 4, "12-15"),
                Exercicio1("Levantamento Terra com Barra Hexagonal", 4, "10-12"),
                Exercicio1("Pull-Ups com Pegada Neutra", 4, "12-15"),
                Exercicio1("Pulldown na Máquina (pegada supinada)", 4, "12-15"),
                Exercicio1("Mergulho em Paralelas com Peso Extra", 4, "10-12"),
                Exercicio1("Remada Unilateral com Barra T", 4, "12-15"),
                Exercicio1("Puxada com Triângulo na Polia Alta", 4, "12-15"),
                Exercicio1("T-Bar Row", 4, "12-15"),
                Exercicio1("Pulldown com Corda", 4, "12-15"),
                Exercicio1("Mergulho em Paralelas (pegada larga)", 4, "12-15"),
                Exercicio1("Remada na Máquina", 4, "12-15"),
                Exercicio1("Puxada Horizontal na Máquina", 4, "12-15"),
                Exercicio1("Deadlift com Pegada Alternada", 4, "10-12"),
                Exercicio1("Pull-Ups (pegada neutra) com Peso Extra", 4, "10-12"),
                Exercicio1("Puxada no Cabo (pegada supinada)", 4, "12-15"),
                Exercicio1("Remada Sentada", 4, "12-15"),
                Exercicio1("Pulldown na Máquina (pegada larga)", 4, "12-15"),
                Exercicio1("Pull-Ups (pegada mista)", 4, "12-15"),
                Exercicio1("Puxada no Cabo com Pegada Fechada", 4, "12-15"),
                Exercicio1("Deadlift Sumô", 4, "10-12"),
                Exercicio1("Pull-Ups (pegada larga) com Pegada Neutra", 4, "12-15")
            )
        }

        fun treinoDefinicaoCostas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Puxada na Polia Alta (pegada larga)", 4, "15-20"),
                Exercicio1("Levantamento Terra", 4, "12-15"),
                Exercicio1("Barra Fixa (pronada)", 4, "15-20"),
                Exercicio1("Remada Curvada", 4, "15-20"),
                Exercicio1("Puxada na Polia Baixa (pegada supinada)", 4, "15-20"),
                Exercicio1("Pull-Ups (pegada larga)", 4, "15-20"),
                Exercicio1("Remada Cavalinho", 4, "15-20"),
                Exercicio1("Pulldown com Barra (pegada aberta)", 4, "15-20"),
                Exercicio1("Mergulho em Paralelas", 4, "15-20"),
                Exercicio1("Remada Unilateral com Halteres", 4, "15-20"),
                Exercicio1("Pull-Ups (pegada supinada)", 4, "15-20"),
                Exercicio1("Puxada no Cabo com Pegada Neutra", 4, "15-20"),
                Exercicio1("Bent Over Rows com Barra", 4, "15-20"),
                Exercicio1("Pulldown na Máquina", 4, "15-20"),
                Exercicio1("Remada T", 4, "15-20"),
                Exercicio1("Puxada Alta com Corda", 4, "15-20"),
                Exercicio1("Deadlift Romano", 4, "12-15"),
                Exercicio1("Pull-Ups com Peso Extra", 4, "12-15"),
                Exercicio1("Puxada Fechada na Polia Alta", 4, "15-20"),
                Exercicio1("Remada Baixa com Barra T", 4, "15-20"),
                Exercicio1("Puxada na Máquina Hammer Strength", 4, "15-20"),
                Exercicio1("Levantamento Terra com Barra Hexagonal", 4, "12-15"),
                Exercicio1("Pull-Ups com Pegada Neutra", 4, "15-20"),
                Exercicio1("Pulldown na Máquina (pegada supinada)", 4, "15-20"),
                Exercicio1("Mergulho em Paralelas com Peso Extra", 4, "12-15"),
                Exercicio1("Remada Unilateral com Barra T", 4, "15-20"),
                Exercicio1("Puxada com Triângulo na Polia Alta", 4, "15-20"),
                Exercicio1("T-Bar Row", 4, "15-20"),
                Exercicio1("Pulldown com Corda", 4, "15-20"),
                Exercicio1("Mergulho em Paralelas (pegada larga)", 4, "15-20"),
                Exercicio1("Remada na Máquina", 4, "15-20"),
                Exercicio1("Puxada Horizontal na Máquina", 4, "15-20"),
                Exercicio1("Deadlift com Pegada Alternada", 4, "12-15"),
                Exercicio1("Pull-Ups (pegada neutra) com Peso Extra", 4, "12-15"),
                Exercicio1("Puxada no Cabo (pegada supinada)", 4, "15-20"),
                Exercicio1("Remada Sentada", 4, "15-20"),
                Exercicio1("Pulldown na Máquina (pegada larga)", 4, "15-20"),
                Exercicio1("Pull-Ups (pegada larga) com Pegada Neutra", 4, "15-20")
            )
        }

    }

}

class TreinoPerna {
    companion object {

    }
}