package com.simpletask.e_personal

import com.simpletask.e_personal.Exercicio as Exercicio1

data class Exercicio(val nome: String, val series: Int, val repeticoes: String)

class TreinoPeito {
    companion object {
        fun treinoEmagrecimento(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Supino Inclinado com Barra", 3, "12-15"),
                Exercicio1("Supino Declinado com Halteres", 3, "12-15"),
                Exercicio1("Crucifixo com Cabos", 3, "12-15"),
                Exercicio1("Pull-Over com Halteres", 3, "12-15"),
                Exercicio1("Flexão de Braços (joelhos apoiados, se necessário)", 3, "15-20"),
                Exercicio1("Supino Reto com Barra", 3, "12-15"),
                Exercicio1("Supino Declinado com Barra", 3, "12-15"),
                Exercicio1("Mergulhos em Paralelas", 3, "12-15"),
                Exercicio1("Flexão de Braços com Pernas Elevadas", 3, "15-20"),
                Exercicio1("Aperto de Mão no Pulley", 3, "12-15"),
                Exercicio1("Supino com Pegada Fechada", 3, "12-15"),
                Exercicio1("Flyes com Halteres", 3, "12-15"),
                Exercicio1("Supino Inclinado na Máquina", 3, "12-15"),
                Exercicio1("Push-Up Plyo (flexões explosivas com salto)", 3, "12-15"),
                Exercicio1("Supino Declinado na Máquina", 3, "12-15"),
                Exercicio1("Supino com Pegada Larga", 3, "12-15"),
                Exercicio1("Cross-Over com Cabos", 3, "12-15"),
                Exercicio1("Supino na Máquina Smith", 3, "12-15"),
                Exercicio1("Flexões Declinadas", 3, "15-20"),
                Exercicio1("Supino com Pegada Neutra", 3, "12-15"),
                Exercicio1("Pull-Over na Máquina", 3, "12-15"),
                Exercicio1("Flexões com os Pés Elevados", 3, "15-20"),
                Exercicio1("Mergulhos com Bola Suíça", 3, "12-15"),
                Exercicio1("Supino Reto com Halteres", 3, "12-15"),
                Exercicio1("Supino Inclinado com Barra", 3, "12-15"),
                Exercicio1("Crucifixo na Máquina", 3, "12-15"),
                Exercicio1("Push-Ups com Deslize", 3, "15-20"),
                Exercicio1("Aperto de Mão na Máquina", 3, "12-15"),
                Exercicio1("Supino com Corda", 3, "12-15"),
                Exercicio1("Flexões Explosivas", 3, "12-15"),
                Exercicio1("Flyes Inclinados com Halteres", 3, "12-15"),
                Exercicio1("Mergulhos em Barras Paralelas", 3, "12-15"),
                Exercicio1("Supino na Máquina Hammer Strength", 3, "12-15"),
                Exercicio1("Flexões com Toque no Ombro", 3, "15-20"),
                Exercicio1("Crucifixo Declinado na Máquina", 3, "12-15"),
                Exercicio1("Supino Inclinado com Halteres Leves", 3, "15-20"),
                Exercicio1("Supino Declinado com Halteres", 3, "12-15"),
                Exercicio1("Push-Ups de Tríceps", 3, "12-15"),
                Exercicio1("Flexões com Rotação (alternar entre as mãos)", 3, "12-15"),
                Exercicio1("Mergulhos no Banco (uso de bancos inclinados)", 3, "12-15"),
                Exercicio1("Flexões com Pernas no Banco", 3, "15-20"),
            )
        }

        fun treinoHipertrofia(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Supino Reto com Barra", 4, "8-10"),
                Exercicio1("Supino Inclinado com Halteres", 4, "8-10"),
                Exercicio1("Supino Declinado com Barra", 4, "8-10"),
                Exercicio1("Crucifixo Inclinado com Halteres", 4, "10-12"),
                Exercicio1("Mergulhos em Paralelas", 4, "10-12"),
                Exercicio1("Supino Inclinado na Máquina", 4, "10-12"),
                Exercicio1("Supino Reto na Máquina Smith", 4, "8-10"),
                Exercicio1("Crucifixo na Máquina", 4, "10-12"),
                Exercicio1("Flyes com Cabos", 4, "10-12"),
                Exercicio1("Supino com Pegada Fechada", 4, "10-12"),
                Exercicio1("Supino com Pegada Ampla", 4, "8-10"),
                Exercicio1("Flexões Ponderadas (com peso extra)", 4, "8-10"),
                Exercicio1("Peck Deck (máquina de peitoral)", 4, "10-12"),
                Exercicio1("Supino Declinado na Máquina", 4, "10-12"),
                Exercicio1("Aperto de Mão no Pulley Alto", 4, "10-12"),
                Exercicio1("Cross-Over com Corda", 4, "12-15"),
                Exercicio1("Supino com Pegada Neutra na Máquina Smith", 4, "10-12"),
                Exercicio1("Flexões com Parada (parar no meio do movimento)", 4, "10-12"),
                Exercicio1("Mergulhos no Banco (uso de bancos inclinados)", 4, "10-12"),
                Exercicio1("Supino na Máquina Hammer Strength", 4, "8-10"),
                Exercicio1("Flexões em Barras Paralelas", 4, "10-12"),
                Exercicio1("Flexões Declinadas", 4, "12-15"),
                Exercicio1("Flyes Declinados com Halteres", 4, "10-12"),
                Exercicio1("Supino Inclinado com Halteres Leves", 4, "12-15"),
                Exercicio1("Pullovers na Máquina", 4, "10-12"),
                Exercicio1("Flexões com Peso Corporal", 4, "12-15"),
                Exercicio1("Flyes Pec-Deck (máquina de voar)", 4, "12-15"),
                Exercicio1("Supino Declinado com Halteres Leves", 4, "12-15"),
                Exercicio1("Push-Ups na Bola Suíça", 4, "10-12"),
                Exercicio1("Supino com Pegada Larga na Máquina Smith", 4, "10-12"),
                Exercicio1("Mergulhos em Bancos Paralelos com Peso", 4, "10-12"),
                Exercicio1("Pullovers com Barra", 4, "10-12"),
                Exercicio1("Flyes com Halteres Declinados", 4, "10-12"),
                Exercicio1("Supino Inclinado com Halteres Pesados", 4, "8-10"),
                Exercicio1("Flexões no Solo", 4, "12-15"),
                Exercicio1("Supino Reto com Halteres Pesados", 4, "8-10"),
                Exercicio1("Crucifixo na Máquina Cross-Over", 4, "10-12"),
                Exercicio1("Flexões com os Pés Elevados", 4, "12-15"),
                Exercicio1("Flexões Declinadas com Peso Corporal", 4, "12-15"),
                Exercicio1("Supino com Pegada Fechada na Máquina", 4, "10-12"),
                Exercicio1("Supino com Corda na Polia Alta", 4, "10-12"),
            )
        }

        fun treinoDefinicao(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Supino Declinado com Barra (peso moderado)", 4, "10-12"),
                Exercicio1("Supino Inclinado com Halteres", 4, "10-12"),
                Exercicio1("Crucifixo com Cabos (contração muscular)", 4, "12-15"),
                Exercicio1("Flexões Explosivas", 4, "12-15"),
                Exercicio1("Pulldown na Máquina (parte superior do peito)", 4, "12-15"),
                Exercicio1("Supino Declinado com Halteres (peso moderado)", 4, "10-12"),
                Exercicio1("Cross-Over com Cabos (variação de ângulo)", 4, "12-15"),
                Exercicio1("Flexões em Diamante (mãos próximas)", 4, "12-15"),
                Exercicio1("Flyes com Halteres (peso moderado)", 4, "10-12"),
                Exercicio1("Mergulhos em Paralelas (contração muscular)", 4, "12-15"),
                Exercicio1("Supino com Pegada Neutra na Máquina", 4, "10-12"),
                Exercicio1("Flexões na Bola de Estabilidade (trabalho do core)", 4, "12-15"),
                Exercicio1("Supino na Máquina Smith (peso moderado)", 4, "10-12"),
                Exercicio1("Flexões com Rotação (alternar entre as mãos)", 4, "12-15"),
                Exercicio1("Flexões Declinadas (peso corporal ou com peso extra)", 4, "12-15"),
                Exercicio1("Supino Declinado na Máquina (peso moderado)", 4, "10-12"),
                Exercicio1("Flyes Declinados na Máquina", 4, "12-15"),
                Exercicio1("Supino na Máquina Hammer Strength (peso moderado)", 4, "10-12"),
                Exercicio1("Cross-Over com Corda (variação de amplitude)", 4, "12-15"),
                Exercicio1("Flexões Pliométricas (saltos explosivos)", 4, "12-15"),
                Exercicio1("Supino Inclinado com Barra (peso moderado)", 4, "10-12"),
                Exercicio1("Supino Declinado com Barra (peso moderado)", 4, "10-12"),
                Exercicio1("Crucifixo com Cabos (contração muscular)", 4, "12-15"),
                Exercicio1("Flexões Explosivas", 4, "12-15"),
                Exercicio1("Pulldown na Máquina (parte superior do peito)", 4, "12-15"),
                Exercicio1("Supino Declinado com Halteres (peso moderado)", 4, "10-12"),
                Exercicio1("Cross-Over com Cabos (variação de ângulo)", 4, "12-15"),
                Exercicio1("Flexões em Diamante (mãos próximas)", 4, "12-15"),
                Exercicio1("Flyes com Halteres (peso moderado)", 4, "10-12"),
                Exercicio1("Mergulhos em Paralelas (contração muscular)", 4, "12-15"),
                Exercicio1("Supino com Pegada Neutra na Máquina", 4, "10-12"),
                Exercicio1("Flexões na Bola de Estabilidade (trabalho do core)", 4, "12-15"),
                Exercicio1("Supino na Máquina Smith (peso moderado)", 4, "10-12"),
                Exercicio1("Flexões com Rotação (alternar entre as mãos)", 4, "12-15"),
                Exercicio1("Flexões Declinadas (peso corporal ou com peso extra)", 4, "12-15"),
                Exercicio1("Supino Declinado na Máquina (peso moderado)", 4, "10-12"),
                Exercicio1("Flyes Declinados na Máquina", 4, "12-15"),
                Exercicio1("Supino na Máquina Hammer Strength (peso moderado)", 4, "10-12"),
                Exercicio1("Cross-Over com Corda (variação de amplitude)", 4, "12-15"),
                Exercicio1("Flexões Pliométricas (saltos explosivos)", 4, "12-15")
            )
        }
    }

}

class TreinoCostas {
    companion object {
        fun treinoHipertrofiaCostas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Puxada na Polia Alta (pegada larga)", 4, "8-10"),
                Exercicio1("Levantamento Terra", 4, "6-8"),
                Exercicio1("Barra Fixa (pronada)", 4, "8-10"),
                Exercicio1("Remada Curvada", 4, "8-10"),
                Exercicio1("Puxada na Polia Baixa (pegada supinada)", 4, "8-10"),
                Exercicio1("Pull-Ups (pegada larga)", 4, "8-10"),
                Exercicio1("Remada Cavalinho", 4, "10-12"),
                Exercicio1("Pulldown com Barra (pegada aberta)", 4, "8-10"),
                Exercicio1("Mergulho em Paralelas", 4, "8-10"),
                Exercicio1("Remada Unilateral com Halteres", 4, "10-12"),
                Exercicio1("Pull-Ups (pegada supinada)", 4, "8-10"),
                Exercicio1("Puxada no Cabo com Pegada Neutra", 4, "8-10"),
                Exercicio1("Bent Over Rows com Barra", 4, "8-10"),
                Exercicio1("Pulldown na Máquina", 4, "8-10"),
                Exercicio1("Remada T", 4, "10-12"),
                Exercicio1("Puxada Alta com Corda", 4, "10-12"),
                Exercicio1("Deadlift Romano", 4, "6-8"),
                Exercicio1("Pull-Ups com Peso Extra", 4, "6-8"),
                Exercicio1("Puxada Fechada na Polia Alta", 4, "8-10"),
                Exercicio1("Remada Baixa com Barra T", 4, "8-10"),
                Exercicio1("Puxada na Máquina Hammer Strength", 4, "8-10"),
                Exercicio1("Levantamento Terra com Barra Hexagonal", 4, "6-8"),
                Exercicio1("Pull-Ups com Pegada Neutra", 4, "8-10"),
                Exercicio1("Pulldown na Máquina (pegada supinada)", 4, "10-12"),
                Exercicio1("Mergulho em Paralelas com Peso Extra", 4, "6-8"),
                Exercicio1("Remada Unilateral com Barra T", 4, "8-10"),
                Exercicio1("Puxada com Triângulo na Polia Alta", 4, "8-10"),
                Exercicio1("T-Bar Row", 4, "8-10"),
                Exercicio1("Pulldown com Corda", 4, "10-12"),
                Exercicio1("Mergulho em Paralelas (pegada larga)", 4, "8-10"),
                Exercicio1("Remada na Máquina", 4, "8-10"),
                Exercicio1("Puxada Horizontal na Máquina", 4, "8-10"),
                Exercicio1("Deadlift com Pegada Alternada", 4, "6-8"),
                Exercicio1("Pull-Ups (pegada neutra) com Peso Extra", 4, "6-8"),
                Exercicio1("Puxada no Cabo (pegada supinada)", 4, "8-10"),
                Exercicio1("Remada Sentada", 4, "8-10"),
                Exercicio1("Pulldown na Máquina (pegada larga)", 4, "10-12"),
                Exercicio1("Pull-Ups (pegada mista)", 4, "8-10"),
                Exercicio1("Puxada no Cabo com Pegada Fechada", 4, "8-10"),
                Exercicio1("Deadlift Sumô", 4, "6-8"),
                Exercicio1("Pull-Ups (pegada larga) com Pegada Neutra", 4, "8-10")
            )
        }

        fun treinoEmagrecimentoCostas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Puxada na Polia Alta (pegada larga)", 4, "12-15"),
                Exercicio1("Levantamento Terra", 4, "10-12"),
                Exercicio1("Barra Fixa (pronada)", 4, "12-15"),
                Exercicio1("Remada Curvada", 4, "12-15"),
                Exercicio1("Puxada na Polia Baixa (pegada supinada)", 4, "12-15"),
                Exercicio1("Pull-Ups (pegada larga)", 4, "12-15"),
                Exercicio1("Remada Cavalinho", 4, "12-15"),
                Exercicio1("Pulldown com Barra (pegada aberta)", 4, "12-15"),
                Exercicio1("Mergulho em Paralelas", 4, "12-15"),
                Exercicio1("Remada Unilateral com Halteres", 4, "12-15"),
                Exercicio1("Pull-Ups (pegada supinada)", 4, "12-15"),
                Exercicio1("Puxada no Cabo com Pegada Neutra", 4, "12-15"),
                Exercicio1("Bent Over Rows com Barra", 4, "12-15"),
                Exercicio1("Pulldown na Máquina", 4, "12-15"),
                Exercicio1("Remada T", 4, "12-15"),
                Exercicio1("Puxada Alta com Corda", 4, "12-15"),
                Exercicio1("Deadlift Romano", 4, "10-12"),
                Exercicio1("Pull-Ups com Peso Extra", 4, "10-12"),
                Exercicio1("Puxada Fechada na Polia Alta", 4, "12-15"),
                Exercicio1("Remada Baixa com Barra T", 4, "12-15"),
                Exercicio1("Puxada na Máquina Hammer Strength", 4, "12-15"),
                Exercicio1("Levantamento Terra com Barra Hexagonal", 4, "10-12"),
                Exercicio1("Pull-Ups com Pegada Neutra", 4, "12-15"),
                Exercicio1("Pulldown na Máquina (pegada supinada)", 4, "12-15"),
                Exercicio1("Mergulho em Paralelas com Peso Extra", 4, "10-12"),
                Exercicio1("Remada Unilateral com Barra T", 4, "12-15"),
                Exercicio1("Puxada com Triângulo na Polia Alta", 4, "12-15"),
                Exercicio1("T-Bar Row", 4, "12-15"),
                Exercicio1("Pulldown com Corda", 4, "12-15"),
                Exercicio1("Mergulho em Paralelas (pegada larga)", 4, "12-15"),
                Exercicio1("Remada na Máquina", 4, "12-15"),
                Exercicio1("Puxada Horizontal na Máquina", 4, "12-15"),
                Exercicio1("Deadlift com Pegada Alternada", 4, "10-12"),
                Exercicio1("Pull-Ups (pegada neutra) com Peso Extra", 4, "10-12"),
                Exercicio1("Puxada no Cabo (pegada supinada)", 4, "12-15"),
                Exercicio1("Remada Sentada", 4, "12-15"),
                Exercicio1("Pulldown na Máquina (pegada larga)", 4, "12-15"),
                Exercicio1("Pull-Ups (pegada mista)", 4, "12-15"),
                Exercicio1("Puxada no Cabo com Pegada Fechada", 4, "12-15"),
                Exercicio1("Deadlift Sumô", 4, "10-12"),
                Exercicio1("Pull-Ups (pegada larga) com Pegada Neutra", 4, "12-15")
            )
        }

        fun treinoDefinicaoCostas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Puxada na Polia Alta (pegada larga)", 4, "15-20"),
                Exercicio1("Levantamento Terra", 4, "12-15"),
                Exercicio1("Barra Fixa (pronada)", 4, "15-20"),
                Exercicio1("Remada Curvada", 4, "15-20"),
                Exercicio1("Puxada na Polia Baixa (pegada supinada)", 4, "15-20"),
                Exercicio1("Pull-Ups (pegada larga)", 4, "15-20"),
                Exercicio1("Remada Cavalinho", 4, "15-20"),
                Exercicio1("Pulldown com Barra (pegada aberta)", 4, "15-20"),
                Exercicio1("Mergulho em Paralelas", 4, "15-20"),
                Exercicio1("Remada Unilateral com Halteres", 4, "15-20"),
                Exercicio1("Pull-Ups (pegada supinada)", 4, "15-20"),
                Exercicio1("Puxada no Cabo com Pegada Neutra", 4, "15-20"),
                Exercicio1("Bent Over Rows com Barra", 4, "15-20"),
                Exercicio1("Pulldown na Máquina", 4, "15-20"),
                Exercicio1("Remada T", 4, "15-20"),
                Exercicio1("Puxada Alta com Corda", 4, "15-20"),
                Exercicio1("Deadlift Romano", 4, "12-15"),
                Exercicio1("Pull-Ups com Peso Extra", 4, "12-15"),
                Exercicio1("Puxada Fechada na Polia Alta", 4, "15-20"),
                Exercicio1("Remada Baixa com Barra T", 4, "15-20"),
                Exercicio1("Puxada na Máquina Hammer Strength", 4, "15-20"),
                Exercicio1("Levantamento Terra com Barra Hexagonal", 4, "12-15"),
                Exercicio1("Pull-Ups com Pegada Neutra", 4, "15-20"),
                Exercicio1("Pulldown na Máquina (pegada supinada)", 4, "15-20"),
                Exercicio1("Mergulho em Paralelas com Peso Extra", 4, "12-15"),
                Exercicio1("Remada Unilateral com Barra T", 4, "15-20"),
                Exercicio1("Puxada com Triângulo na Polia Alta", 4, "15-20"),
                Exercicio1("T-Bar Row", 4, "15-20"),
                Exercicio1("Pulldown com Corda", 4, "15-20"),
                Exercicio1("Mergulho em Paralelas (pegada larga)", 4, "15-20"),
                Exercicio1("Remada na Máquina", 4, "15-20"),
                Exercicio1("Puxada Horizontal na Máquina", 4, "15-20"),
                Exercicio1("Deadlift com Pegada Alternada", 4, "12-15"),
                Exercicio1("Pull-Ups (pegada neutra) com Peso Extra", 4, "12-15"),
                Exercicio1("Puxada no Cabo (pegada supinada)", 4, "15-20"),
                Exercicio1("Remada Sentada", 4, "15-20"),
                Exercicio1("Pulldown na Máquina (pegada larga)", 4, "15-20"),
                Exercicio1("Pull-Ups (pegada larga) com Pegada Neutra", 4, "15-20")
            )
        }

    }

}

class TreinoPerna {
    companion object {
        fun treinoHipertrofiaPernas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Agachamento Livre", 4, "8-10"),
                Exercicio1("Leg Press 45°", 4, "10-12"),
                Exercicio1("Afundo com Barra", 4, "10-12"),
                Exercicio1("Cadeira Extensora", 4, "12-15"),
                Exercicio1("Stiff", 4, "8-10"),
                Exercicio1("Mesa Flexora", 4, "12-15"),
                Exercicio1("Agachamento Hack", 4, "10-12"),
                Exercicio1("Prensa 45°", 4, "10-12"),
                Exercicio1("Cadeira Flexora", 4, "12-15"),
                Exercicio1("Passada com Halteres", 4, "10-12"),
                Exercicio1("Elevação de Panturrilhas Sentado", 4, "12-15"),
                Exercicio1("Agachamento com Salto", 4, "8-10"),
                Exercicio1("Extensão de Quadril no Solo", 4, "12-15"),
                Exercicio1("Leg Press 90°", 4, "10-12"),
                Exercicio1("Cadeira Adutora", 4, "12-15"),
                Exercicio1("Caminhada no Leg Press", 4, "10-12"),
                Exercicio1("Afundo com Barra Smith", 4, "10-12"),
                Exercicio1("Cadeira Abdutora", 4, "12-15"),
                Exercicio1("Agachamento Frontal", 4, "8-10"),
                Exercicio1("Cadeira Extensora Unilateral", 4, "12-15"),
                Exercicio1("Mesa Flexora Unilateral", 4, "12-15"),
                Exercicio1("Step Up", 4, "10-12"),
                Exercicio1("Elevação de Panturrilhas em Pé", 4, "12-15"),
                Exercicio1("Agachamento Búlgaro", 4, "10-12"),
                Exercicio1("Cadeira Flexora Unilateral", 4, "12-15"),
                Exercicio1("Mesa Flexora 45°", 4, "12-15"),
                Exercicio1("Agachamento Sumô", 4, "8-10"),
                Exercicio1("Extensão de Quadril com Halteres", 4, "12-15"),
                Exercicio1("Máquina de Abdução de Quadril", 4, "12-15"),
                Exercicio1("Agachamento na Smith Machine", 4, "8-10"),
                Exercicio1("Prensa 90°", 4, "10-12"),
                Exercicio1("Afundo com Barra Guiada", 4, "10-12"),
                Exercicio1("Cadeira Flexora com Máquina", 4, "12-15"),
                Exercicio1("Hack Machine", 4, "10-12"),
                Exercicio1("Cadeira Extensora Unilateral", 4, "12-15"),
                Exercicio1("Leg Press Horizontal", 4, "10-12"),
                Exercicio1("Elevação de Panturrilhas em Máquina", 4, "12-15"),
                Exercicio1("Afundo com Halteres", 4, "10-12"),
                Exercicio1("Mesa Flexora 90°", 4, "12-15"),
                Exercicio1("Passada no Smith Machine", 4, "10-12"),
                Exercicio1("Elevação de Panturrilhas Sentado (máquina)", 4, "12-15")
            )
        }

        fun treinoDefinicaoPernas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Agachamento Livre com Barra (peso moderado)", 4, "15-20"),
                Exercicio1("Leg Press 45° com Pés Juntos", 4, "15-20"),
                Exercicio1("Afundo com Barra Guiada", 4, "15-20"),
                Exercicio1("Cadeira Extensora (contração máxima)", 4, "15-20"),
                Exercicio1("Stiff com Barra (peso moderado)", 4, "15-20"),
                Exercicio1("Mesa Flexora (contração máxima)", 4, "15-20"),
                Exercicio1("Agachamento Hack com Barra (peso moderado)", 4, "15-20"),
                Exercicio1("Prensa 45° com Pés Juntos", 4, "15-20"),
                Exercicio1("Cadeira Flexora (contração máxima)", 4, "15-20"),
                Exercicio1("Passada com Halteres (peso moderado)", 4, "15-20"),
                Exercicio1("Elevação de Panturrilhas Sentado (peso moderado)", 4, "15-20"),
                Exercicio1("Agachamento com Salto", 4, "15-20"),
                Exercicio1("Extensão de Quadril no Solo", 4, "15-20"),
                Exercicio1("Leg Press 90° com Pés Juntos", 4, "15-20"),
                Exercicio1("Cadeira Abdutora (contração máxima)", 4, "15-20"),
                Exercicio1("Caminhada no Leg Press", 4, "15-20"),
                Exercicio1("Afundo com Barra Smith (peso moderado)", 4, "15-20"),
                Exercicio1("Cadeira Abdutora (contração máxima)", 4, "15-20"),
                Exercicio1("Agachamento Frontal com Barra (peso moderado)", 4, "15-20"),
                Exercicio1("Cadeira Extensora Unilateral (contração máxima)", 4, "15-20"),
                Exercicio1("Mesa Flexora Unilateral (contração máxima)", 4, "15-20"),
                Exercicio1("Step Up (peso moderado)", 4, "15-20"),
                Exercicio1("Elevação de Panturrilhas em Pé (peso moderado)", 4, "15-20"),
                Exercicio1("Agachamento Búlgaro com Halteres (peso moderado)", 4, "15-20"),
                Exercicio1("Cadeira Flexora Unilateral (contração máxima)", 4, "15-20"),
                Exercicio1("Mesa Flexora 45° (contração máxima)", 4, "15-20"),
                Exercicio1("Agachamento Sumô (peso moderado)", 4, "15-20"),
                Exercicio1("Extensão de Quadril com Halteres (peso moderado)", 4, "15-20"),
                Exercicio1("Máquina de Abdução de Quadril (contração máxima)", 4, "15-20"),
                Exercicio1("Agachamento na Smith Machine (peso moderado)", 4, "15-20"),
                Exercicio1("Prensa 90° com Pés Juntos", 4, "15-20"),
                Exercicio1("Afundo com Barra Guiada (peso moderado)", 4, "15-20"),
                Exercicio1("Cadeira Flexora com Máquina (contração máxima)", 4, "15-20"),
                Exercicio1("Hack Machine com Barra (peso moderado)", 4, "15-20"),
                Exercicio1("Cadeira Extensora Unilateral (contração máxima)", 4, "15-20"),
                Exercicio1("Leg Press Horizontal com Pés Juntos", 4, "15-20"),
                Exercicio1("Elevação de Panturrilhas em Máquina (peso moderado)", 4, "15-20"),
                Exercicio1("Afundo com Halteres (peso moderado)", 4, "15-20"),
                Exercicio1("Mesa Flexora 90° (contração máxima)", 4, "15-20"),
                Exercicio1("Passada no Smith Machine (peso moderado)", 4, "15-20"),
                Exercicio1("Elevação de Panturrilhas Sentado (máquina, peso moderado)", 4, "15-20")
            )
        }

        fun treinoEmagrecimentoPernas(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Esteira (corrida leve)", 1, "20-30 minutos"),
                Exercicio1("Bicicleta Ergométrica (ritmo moderado)", 1, "20-30 minutos"),
                Exercicio1("Caminhada ao Ar Livre (ritmo moderado)", 1, "20-30 minutos"),
                Exercicio1("Subida de Escadas (ritmo moderado)", 1, "20-30 minutos"),
                Exercicio1("Pular Corda (ritmo moderado)", 1, "20-30 minutos"),
                Exercicio1("Agachamento Corporal", 4, "15-20 repetições"),
                Exercicio1("Afundo sem Peso", 4, "15-20 repetições"),
                Exercicio1("Elevação de Panturrilhas em Pé (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Máquina de Abdução de Quadril (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Máquina de Adução de Quadril (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Leg Press Horizontal (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Cadeira Extensora (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Cadeira Flexora (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Elevação de Panturrilhas Sentado (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Caminhada Lateral (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Agachamento Isométrico (segurar por 30 segundos)", 4, "3 séries"),
                Exercicio1("Prancha Abdominal (segurar por 30 segundos)", 4, "3 séries"),
                Exercicio1("Elevação de Pernas em Supino Declinado (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Bicicleta no Chão (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Agachamento com Salto (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Afundo com Salto (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Burpees", 4, "15-20 repetições"),
                Exercicio1("Mountain Climbers", 4, "15-20 repetições"),
                Exercicio1("Agachamento com Toque na Ponta dos Pés (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Pular Corda (ritmo rápido)", 1, "20-30 minutos"),
                Exercicio1("Escalador (Mountain Climbers com ritmo rápido)", 4, "15-20 repetições"),
                Exercicio1("Salto em Caixa (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Sprint (corrida de alta intensidade por 20-30 segundos)", 4, "4 séries"),
                Exercicio1("Jump Squat (agachamento com salto)", 4, "15-20 repetições"),
                Exercicio1("Cadeira Extensora com uma Perna (sem peso)", 4, "15-20 repetições por perna"),
                Exercicio1("Elevação de Panturrilhas em Pé na Borda (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Agachamento Isométrico com as Costas na Parede (segurar por 30 segundos)", 4, "3 séries"),
                Exercicio1("Prancha Lateral (segurar por 30 segundos de cada lado)", 4, "3 séries"),
                Exercicio1("Agachamento com Salto e Giro (sem peso)", 4, "15-20 repetições"),
                Exercicio1("Lunges com Rotação do Tronco (sem peso)", 4, "15-20 repetições por perna"),
                Exercicio1("Escada de Agilidade (ritmo moderado)", 1, "20-30 minutos"),
                Exercicio1("Sprint em Subida (corrida de alta intensidade por 20-30 segundos em subida)", 4, "4 séries"),
                Exercicio1("Agachamento Isométrico com os Braços Estendidos (segurar por 30 segundos)", 4, "3 séries"),
                Exercicio1("Bicicleta Ergométrica (treino intervalado, alternando entre alta e baixa intensidade)", 1, "20-30 minutos")
            )
        }

    }
}

class TreinoTriceps {
    companion object {
        fun treinoHipertrofiaTriceps(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Tríceps Pulldown na Polia Alta (barra reta)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Alta (barra V)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Alta (corda)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (barra reta)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (barra V)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (corda)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Testa com Barra Reta (supino fechado)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Testa com Barra W (supino fechado)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Testa com Halteres", 4, "8-10 repetições"),
                Exercicio1("Tríceps na Máquina (pegada V)", 4, "8-10 repetições"),
                Exercicio1("Tríceps na Máquina (pegada neutra)", 4, "8-10 repetições"),
                Exercicio1("Tríceps na Máquina (pegada supinada)", 4, "8-10 repetições"),
                Exercicio1("Tríceps na Máquina (pegada pronada)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Kickback com Halteres", 4, "8-10 repetições por braço"),
                Exercicio1("Tríceps Kickback com Barra", 4, "8-10 repetições"),
                Exercicio1("Tríceps Kickback com Anilha", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Supinada", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Neutra", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Pronada", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Corda", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Barra V", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta (Pegada Supinada)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta (Pegada Pronada)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Barra V (Pegada Supinada)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Barra V (Pegada Pronada)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Supinada)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Pronada)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Neutra)", 4, "8-10 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada em Martelo)", 4, "8-10 repetições"),
                Exercicio1(
                    "Tríceps Pulley com Barra Reta (Pegada Supinada e Larga)",
                    4,
                    "8-10 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Barra Reta (Pegada Pronada e Larga)",
                    4,
                    "8-10 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Barra V (Pegada Supinada e Larga)",
                    4,
                    "8-10 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Barra V (Pegada Pronada e Larga)",
                    4,
                    "8-10 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Corda (Pegada Supinada e Larga)",
                    4,
                    "8-10 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Corda (Pegada Pronada e Larga)",
                    4,
                    "8-10 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Corda (Pegada Neutra e Larga)",
                    4,
                    "8-10 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Corda (Pegada em Martelo e Larga)",
                    4,
                    "8-10 repetições"
                )
            )
        }

        fun treinoDefinicaoTriceps(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Tríceps Pulldown na Polia Alta (barra reta)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Alta (barra V)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Alta (corda)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (barra reta)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (barra V)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (corda)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Testa com Barra Reta (supino fechado)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Testa com Barra W (supino fechado)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Testa com Halteres", 4, "15-20 repetições"),
                Exercicio1("Tríceps na Máquina (pegada V)", 4, "15-20 repetições"),
                Exercicio1("Tríceps na Máquina (pegada neutra)", 4, "15-20 repetições"),
                Exercicio1("Tríceps na Máquina (pegada supinada)", 4, "15-20 repetições"),
                Exercicio1("Tríceps na Máquina (pegada pronada)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Kickback com Halteres", 4, "15-20 repetições por braço"),
                Exercicio1("Tríceps Kickback com Barra", 4, "15-20 repetições"),
                Exercicio1("Tríceps Kickback com Anilha", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Supinada", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Neutra", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Pronada", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Corda", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Barra V", 4, "15-20 repetições"),
                Exercicio1(
                    "Tríceps Pulley com Barra Reta (Pegada Supinada)",
                    4,
                    "15-20 repetições"
                ),
                Exercicio1("Tríceps Pulley com Barra Reta (Pegada Pronada)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Barra V (Pegada Supinada)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Barra V (Pegada Pronada)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Supinada)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Pronada)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Neutra)", 4, "15-20 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada em Martelo)", 4, "15-20 repetições"),
                Exercicio1(
                    "Tríceps Pulley com Barra Reta (Pegada Supinada e Larga)",
                    4,
                    "15-20 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Barra Reta (Pegada Pronada e Larga)",
                    4,
                    "15-20 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Barra V (Pegada Supinada e Larga)",
                    4,
                    "15-20 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Barra V (Pegada Pronada e Larga)",
                    4,
                    "15-20 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Corda (Pegada Supinada e Larga)",
                    4,
                    "15-20 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Corda (Pegada Pronada e Larga)",
                    4,
                    "15-20 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Corda (Pegada Neutra e Larga)",
                    4,
                    "15-20 repetições"
                ),
                Exercicio1(
                    "Tríceps Pulley com Corda (Pegada em Martelo e Larga)",
                    4,
                    "15-20 repetições"
                )
            )
        }

        fun treinoEmagrecimentoTriceps(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Tríceps Pulldown na Polia Alta (barra reta)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Alta (barra V)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Alta (corda)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (barra reta)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (barra V)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulldown na Polia Baixa (corda)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Testa com Barra Reta (supino fechado)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Testa com Barra W (supino fechado)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Testa com Halteres", 4, "12-15 repetições"),
                Exercicio1("Tríceps na Máquina (pegada V)", 4, "12-15 repetições"),
                Exercicio1("Tríceps na Máquina (pegada neutra)", 4, "12-15 repetições"),
                Exercicio1("Tríceps na Máquina (pegada supinada)", 4, "12-15 repetições"),
                Exercicio1("Tríceps na Máquina (pegada pronada)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Kickback com Halteres", 4, "12-15 repetições por braço"),
                Exercicio1("Tríceps Kickback com Barra", 4, "12-15 repetições"),
                Exercicio1("Tríceps Kickback com Anilha", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Supinada", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Neutra", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Pegada Pronada", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra V", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta (Pegada Supinada)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta (Pegada Pronada)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra V (Pegada Supinada)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra V (Pegada Pronada)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Supinada)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Pronada)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Neutra)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada em Martelo)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta (Pegada Supinada e Larga)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra Reta (Pegada Pronada e Larga)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra V (Pegada Supinada e Larga)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Barra V (Pegada Pronada e Larga)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Supinada e Larga)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Pronada e Larga)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada Neutra e Larga)", 4, "12-15 repetições"),
                Exercicio1("Tríceps Pulley com Corda (Pegada em Martelo e Larga)", 4, "12-15 repetições")
            )}

        }
}

class TreinoBiceps {
    companion object {
        fun treinoHipertrofiaBiceps(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Rosca Direta com Barra Reta", 4, "8-10 repetições"),
                Exercicio1("Rosca Direta com Barra W", 4, "8-10 repetições"),
                Exercicio1("Rosca Direta com Barra EZ", 4, "8-10 repetições"),
                Exercicio1("Rosca Scott", 4, "8-10 repetições"),
                Exercicio1("Rosca Martelo", 4, "8-10 repetições"),
                Exercicio1("Rosca Concentrada", 4, "8-10 repetições"),
                Exercicio1("Rosca Alternada com Halteres", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca 21", 4, "8-10 repetições"),
                Exercicio1("Rosca Inversa", 4, "8-10 repetições"),
                Exercicio1("Rosca com Pegador", 4, "8-10 repetições"),
                Exercicio1("Rosca Martelo Alternada", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Spider", 4, "8-10 repetições"),
                Exercicio1("Rosca Concentrada na Máquina", 4, "8-10 repetições"),
                Exercicio1("Rosca Inversa na Máquina", 4, "8-10 repetições"),
                Exercicio1("Rosca Alternada na Máquina", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca na Máquina (bíceps máquina)", 4, "8-10 repetições"),
                Exercicio1("Rosca com Barra na Máquina (bíceps máquina)", 4, "8-10 repetições"),
                Exercicio1("Rosca 21 na Máquina (bíceps máquina)", 4, "8-10 repetições"),
                Exercicio1("Rosca Alternada com Halteres em Pé", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Concentrada em Pé", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca 21 em Pé", 4, "8-10 repetições"),
                Exercicio1("Rosca Direta com Barra Reta (pegada aberta)", 4, "8-10 repetições"),
                Exercicio1("Rosca Direta com Barra W (pegada aberta)", 4, "8-10 repetições"),
                Exercicio1("Rosca Martelo com Barra", 4, "8-10 repetições"),
                Exercicio1("Rosca Martelo Alternada com Barra", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca 21 com Barra", 4, "8-10 repetições"),
                Exercicio1("Rosca Direta com Halteres", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Martelo com Halteres", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Concentrada com Halteres", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Scott com Halteres", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca 21 com Halteres", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca 21 com Barra EZ", 4, "8-10 repetições"),
                Exercicio1("Rosca Direta na Máquina", 4, "8-10 repetições"),
                Exercicio1("Rosca na Máquina (bíceps máquina, pegada supinada)", 4, "8-10 repetições"),
                Exercicio1("Rosca com Barra na Máquina (bíceps máquina, pegada supinada)", 4, "8-10 repetições"),
                Exercicio1("Rosca 21 na Máquina (bíceps máquina, pegada supinada)", 4, "8-10 repetições"),
                Exercicio1("Rosca Alternada com Halteres em Banco Inclinado", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Martelo com Halteres em Banco Inclinado", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Concentrada com Halteres em Banco Inclinado", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca 21 com Halteres em Banco Inclinado", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Alternada com Halteres em Banco Scott", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Martelo com Halteres em Banco Scott", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca Concentrada com Halteres em Banco Scott", 4, "8-10 repetições por braço"),
                Exercicio1("Rosca 21 com Halteres em Banco Scott", 4, "8-10 repetições por braço")
            )
        }

        fun treinoDefinicaoBiceps(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Rosca Direta com Barra Reta (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Direta com Barra W (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Direta com Barra EZ (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Scott (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Martelo (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Concentrada (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Alternada com Halteres (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca 21 (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Inversa (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca com Pegador (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Martelo Alternada (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca Spider (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Concentrada na Máquina (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Inversa na Máquina (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Alternada na Máquina (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca na Máquina (bíceps máquina, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca com Barra na Máquina (bíceps máquina, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca 21 na Máquina (bíceps máquina, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Alternada com Halteres em Pé (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca Concentrada em Pé (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca 21 em Pé (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Direta com Barra Reta (pegada aberta, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Direta com Barra W (pegada aberta, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Martelo com Barra (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Martelo Alternada com Barra (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca 21 com Barra (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Direta com Halteres (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca Martelo com Halteres (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca Concentrada com Halteres (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca Scott com Halteres (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca 21 com Halteres (peso leve)", 4, "15-20 repetições por braço"),
                Exercicio1("Rosca 21 com Barra EZ (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Direta na Máquina (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Martelo na Máquina (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Concentrada na Máquina (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Scott na Máquina (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca 21 na Máquina (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Direta com Corda (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Martelo com Corda (peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Concentrada com Corda (peso leve)", 4, "15-20 repetições")
            )
        }

        fun treinoEmagrecimentoBiceps(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Rosca Direta com Barra Reta (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Direta com Barra W (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Direta com Barra EZ (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Scott (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Martelo (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Concentrada (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Alternada com Halteres (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca 21 (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Inversa (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca com Pegador (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Martelo Alternada (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca Spider (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Concentrada na Máquina (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Inversa na Máquina (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Alternada na Máquina (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca na Máquina (bíceps máquina, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca com Barra na Máquina (bíceps máquina, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca 21 na Máquina (bíceps máquina, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Alternada com Halteres em Pé (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca Concentrada em Pé (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca 21 em Pé (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Direta com Barra Reta (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Direta com Barra W (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Martelo com Barra (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Martelo Alternada com Barra (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca 21 com Barra (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Direta com Halteres (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca Martelo com Halteres (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca Concentrada com Halteres (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca Scott com Halteres (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca 21 com Halteres (peso moderado)", 4, "10-12 repetições por braço"),
                Exercicio1("Rosca 21 com Barra EZ (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Direta com Barra Reta (pegada inversa, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Martelo com Barra W (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Scott com Barra W (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Concentrada com Barra W (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca 21 com Barra W (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca 21 com Barra EZ (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Rosca Direta com Barra Reta (pegada inversa, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Martelo com Barra W (pegada aberta, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Scott com Barra W (pegada aberta, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca Concentrada com Barra W (pegada aberta, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca 21 com Barra W (pegada aberta, peso leve)", 4, "15-20 repetições"),
                Exercicio1("Rosca 21 com Barra EZ (pegada aberta, peso leve)", 4, "15-20 repetições"),
            )
        }


    }
}

class TreinoOmbro {
    companion object {
        fun treinoHipertrofiaOmbro(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Desenvolvimento Militar com Barra (peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Arnold (peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral com Halteres (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral na Máquina (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Halteres (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Barra (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal na Máquina (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Corda (peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (pegada aberta, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (pegada aberta, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Arnold (pegada aberta, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral com Halteres (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral na Máquina (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Halteres (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Barra (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal na Máquina (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Corda (pegada aberta, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (pegada inversa, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (pegada inversa, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Arnold (pegada inversa, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral com Halteres (pegada inversa, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (pegada inversa, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral na Máquina (pegada inversa, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Halteres (pegada inversa, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Barra (pegada inversa, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal na Máquina (pegada inversa, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Corda (pegada inversa, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (pegada neutra, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (pegada neutra, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Arnold (pegada neutra, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral com Halteres (pegada neutra, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (pegada neutra, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral na Máquina (pegada neutra, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Halteres (pegada neutra, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Barra (pegada neutra, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal na Máquina (pegada neutra, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Corda (pegada neutra, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (pegada larga, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (pegada larga, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Arnold (pegada larga, peso moderado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral com Halteres (pegada larga, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (pegada larga, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral na Máquina (pegada larga, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Halteres (pegada larga, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Barra (pegada larga, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal na Máquina (pegada larga, peso moderado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Corda (pegada larga, peso moderado)", 4, "10-12 repetições")
            )
        }

        fun treinoDefinicaoOmbro(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Elevação Frontal com Halteres (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Lateral com Halteres (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Frontal com Barra (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Frontal com Corda (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Frontal na Máquina (leve)", 4, "15-20 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (leve)", 4, "15-20 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (leve)", 4, "15-20 repetições"),
                Exercicio1("Desenvolvimento Arnold (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Lateral com Halteres (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Frontal com Halteres (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Frontal com Barra (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Lateral na Máquina (moderado)", 4, "12-15 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (moderado)", 4, "12-15 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (moderado)", 4, "12-15 repetições"),
                Exercicio1("Desenvolvimento Arnold (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Frontal com Corda (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Lateral com Halteres (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Halteres (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Barra (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral na Máquina (pesado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (pesado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (pesado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Arnold (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Corda (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Halteres (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Frontal com Halteres (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Frontal com Barra (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral na Máquina (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Arnold (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Frontal com Corda (muito pesado)", 4, "8-10 repetições")
            )
        }

        fun treinoEmagrecimentoOmbro(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Elevação Frontal com Halteres (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Lateral com Halteres (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Frontal com Barra (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Frontal com Corda (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Frontal na Máquina (leve)", 4, "15-20 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (leve)", 4, "15-20 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (leve)", 4, "15-20 repetições"),
                Exercicio1("Desenvolvimento Arnold (leve)", 4, "15-20 repetições"),
                Exercicio1("Elevação Lateral com Halteres (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Frontal com Halteres (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Frontal com Barra (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Lateral na Máquina (moderado)", 4, "12-15 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (moderado)", 4, "12-15 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (moderado)", 4, "12-15 repetições"),
                Exercicio1("Desenvolvimento Arnold (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Frontal com Corda (moderado)", 4, "12-15 repetições"),
                Exercicio1("Elevação Lateral com Halteres (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Halteres (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Barra (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral na Máquina (pesado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (pesado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (pesado)", 4, "10-12 repetições"),
                Exercicio1("Desenvolvimento Arnold (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Frontal com Corda (pesado)", 4, "10-12 repetições"),
                Exercicio1("Elevação Lateral com Halteres (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Frontal com Halteres (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral com Polia Baixa (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Frontal com Barra (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Lateral na Máquina (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Barra (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Militar com Halteres (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Desenvolvimento Arnold (muito pesado)", 4, "8-10 repetições"),
                Exercicio1("Elevação Frontal com Corda (muito pesado)", 4, "8-10 repetições")
            )
        }

    }

}

class TreinoQuadriceps {
    companion object {
        fun treinoQuadricepsEmagrecimento(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Agachamento com Barra", 3, "12-15"),
                Exercicio1("Leg Press", 3, "12-15"),
                Exercicio1("Avanço com Halteres", 3, "12-15"),
                Exercicio1("Cadeira Extensora", 3, "12-15"),
                Exercicio1("Agachamento Sumô", 3, "12-15"),
                Exercicio1("Passada", 3, "12-15"),
                Exercicio1("Extensão de Quadril", 3, "12-15"),
                Exercicio1("Agachamento com Smith Machine", 3, "12-15"),
                Exercicio1("Stiff", 3, "12-15"),
                Exercicio1("Prensa 45 graus", 3, "12-15"),
                Exercicio1("Afundo", 3, "12-15"),
                Exercicio1("Agachamento Búlgaro", 3, "12-15"),
                Exercicio1("Gêmeos Sentado", 3, "12-15"),
                Exercicio1("Gêmeos em Pé", 3, "12-15"),
                Exercicio1("Agachamento com Kettlebell", 3, "12-15"),
                Exercicio1("Hack Squat", 3, "12-15"),
                Exercicio1("Caminhada no Smith Machine", 3, "12-15"),
                Exercicio1("Passada na Máquina", 3, "12-15"),
                Exercicio1("Step Up", 3, "12-15"),
                Exercicio1("Caminhada no Leg Press", 3, "12-15"),
                Exercicio1("Agachamento no Hack Smith", 3, "12-15"),
                Exercicio1("Cadeira Extensora Unilateral", 3, "12-15"),
                Exercicio1("Agachamento com Bosu", 3, "12-15"),
                Exercicio1("Leg Press Unilateral", 3, "12-15"),
                Exercicio1("Salto Vertical", 3, "12-15"),
                Exercicio1("Agachamento com Bola Suíça", 3, "12-15"),
                Exercicio1("Agachamento com Peso Corporal", 3, "12-15"),
                Exercicio1("Step na Caixa", 3, "12-15"),
                Exercicio1("Gêmeos na Bola Suíça", 3, "12-15"),
                Exercicio1("Agachamento com Corda", 3, "12-15"),
                Exercicio1("Agachamento na Plataforma Vibratória", 3, "12-15"),
                Exercicio1("Agachamento com Banda de Resistência", 3, "12-15"),
                Exercicio1("Prensa de Pernas", 3, "12-15"),
                Exercicio1("Agachamento com Kettlebell e Salto", 3, "12-15"),
                Exercicio1("Caminhada com Barra", 3, "12-15"),
                Exercicio1("Caminhada com Halteres", 3, "12-15"),
                Exercicio1("Leg Press com Halteres", 3, "12-15"),
                Exercicio1("Agachamento com Barra Guiada", 3, "12-15"),
                Exercicio1("Agachamento com Bola Medicinal", 3, "12-15"),
                Exercicio1("Gêmeos em Pé na Máquina", 3, "12-15")
            )
        }

        fun treinoQuadricepsDefinicao(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Agachamento Frontal", 4, "10-12"),
                Exercicio1("Agachamento Hack", 4, "10-12"),
                Exercicio1("Leg Press", 4, "10-12"),
                Exercicio1("Agachamento com Smith Machine", 4, "10-12"),
                Exercicio1("Afundo com Barra", 4, "10-12"),
                Exercicio1("Extensão de Quadril", 4, "10-12"),
                Exercicio1("Cadeira Extensora", 4, "10-12"),
                Exercicio1("Avanço com Halteres", 4, "10-12"),
                Exercicio1("Agachamento Sumô", 4, "10-12"),
                Exercicio1("Stiff", 4, "10-12"),
                Exercicio1("Agachamento Búlgaro", 4, "10-12"),
                Exercicio1("Leg Press Unilateral", 4, "10-12"),
                Exercicio1("Caminhada no Smith Machine", 4, "10-12"),
                Exercicio1("Passada na Máquina", 4, "10-12"),
                Exercicio1("Step Up com Barra", 4, "10-12"),
                Exercicio1("Agachamento com Bosu", 4, "10-12"),
                Exercicio1("Agachamento com Bola Suíça", 4, "10-12"),
                Exercicio1("Agachamento com Peso Corporal", 4, "10-12"),
                Exercicio1("Step na Caixa", 4, "10-12"),
                Exercicio1("Agachamento com Corda", 4, "10-12"),
                Exercicio1("Agachamento com Banda de Resistência", 4, "10-12"),
                Exercicio1("Prensa de Pernas", 4, "10-12"),
                Exercicio1("Agachamento com Kettlebell e Salto", 4, "10-12"),
                Exercicio1("Caminhada com Barra", 4, "10-12"),
                Exercicio1("Caminhada com Halteres", 4, "10-12"),
                Exercicio1("Leg Press com Halteres", 4, "10-12"),
                Exercicio1("Agachamento com Barra Guiada", 4, "10-12"),
                Exercicio1("Agachamento com Bola Medicinal", 4, "10-12"),
                Exercicio1("Gêmeos em Pé na Máquina", 4, "10-12"),
                Exercicio1("Gêmeos Sentado", 4, "10-12"),
                Exercicio1("Cadeira Adutora", 4, "10-12"),
                Exercicio1("Cadeira Abdutora", 4, "10-12"),
                Exercicio1("Cadeira Flexora", 4, "10-12"),
                Exercicio1("Mesa Flexora", 4, "10-12"),
                Exercicio1("Stiff com Halteres", 4, "10-12"),
                Exercicio1("Prensa 45 graus", 4, "10-12"),
                Exercicio1("Caminhada no Leg Press", 4, "10-12"),
                Exercicio1("Agachamento no Hack Smith", 4, "10-12"),
                Exercicio1("Cadeira Extensora Unilateral", 4, "10-12"),
                Exercicio1("Cadeira Adutora Unilateral", 4, "10-12"),
                Exercicio1("Cadeira Abdutora Unilateral", 4, "10-12"),
                Exercicio1("Gêmeos em Pé com Halteres", 4, "10-12"),
                Exercicio1("Cadeira Abdutora com Halteres", 4, "10-12")
            )
        }

        fun treinoQuadricepsHipertrofia(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Agachamento Livre", 4, "8-10"),
                Exercicio1("Agachamento com Barra", 4, "8-10"),
                Exercicio1("Agachamento Hack", 4, "8-10"),
                Exercicio1("Leg Press", 4, "8-10"),
                Exercicio1("Agachamento com Smith Machine", 4, "8-10"),
                Exercicio1("Afundo com Barra", 4, "8-10"),
                Exercicio1("Avanço com Halteres", 4, "8-10"),
                Exercicio1("Agachamento Sumô", 4, "8-10"),
                Exercicio1("Stiff", 4, "8-10"),
                Exercicio1("Agachamento Búlgaro", 4, "8-10"),
                Exercicio1("Leg Press Unilateral", 4, "8-10"),
                Exercicio1("Caminhada no Smith Machine", 4, "8-10"),
                Exercicio1("Passada na Máquina", 4, "8-10"),
                Exercicio1("Step Up com Barra", 4, "8-10"),
                Exercicio1("Agachamento com Bosu", 4, "8-10"),
                Exercicio1("Agachamento com Bola Suíça", 4, "8-10"),
                Exercicio1("Agachamento com Peso Corporal", 4, "8-10"),
                Exercicio1("Step na Caixa", 4, "8-10"),
                Exercicio1("Agachamento com Corda", 4, "8-10"),
                Exercicio1("Agachamento com Banda de Resistência", 4, "8-10"),
                Exercicio1("Prensa de Pernas", 4, "8-10"),
                Exercicio1("Agachamento com Kettlebell e Salto", 4, "8-10"),
                Exercicio1("Caminhada com Barra", 4, "8-10"),
                Exercicio1("Caminhada com Halteres", 4, "8-10"),
                Exercicio1("Leg Press com Halteres", 4, "8-10"),
                Exercicio1("Agachamento com Barra Guiada", 4, "8-10"),
                Exercicio1("Agachamento com Bola Medicinal", 4, "8-10"),
                Exercicio1("Gêmeos em Pé na Máquina", 4, "8-10"),
                Exercicio1("Gêmeos Sentado", 4, "8-10"),
                Exercicio1("Cadeira Adutora", 4, "8-10"),
                Exercicio1("Cadeira Abdutora", 4, "8-10"),
                Exercicio1("Cadeira Flexora", 4, "8-10"),
                Exercicio1("Mesa Flexora", 4, "8-10"),
                Exercicio1("Stiff com Halteres", 4, "8-10"),
                Exercicio1("Prensa 45 graus", 4, "8-10"),
                Exercicio1("Caminhada no Leg Press", 4, "8-10"),
                Exercicio1("Agachamento no Hack Smith", 4, "8-10"),
                Exercicio1("Cadeira Extensora Unilateral", 4, "8-10"),
                Exercicio1("Cadeira Adutora Unilateral", 4, "8-10"),
                Exercicio1("Cadeira Abdutora Unilateral", 4, "8-10"),
                Exercicio1("Gêmeos em Pé com Halteres", 4, "8-10"),
                Exercicio1("Cadeira Abdutora com Halteres", 4, "8-10")
            )
        }
    }
}

class TreinoPosteriorCoxa {
    companion object {
        fun treinoPosteriorCoixaHipertrofia(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Levantamento Terra", 4, "8-10"),
                Exercicio1("Flexor Horizontal", 4, "8-10"),
                Exercicio1("Flexor Vertical", 4, "8-10"),
                Exercicio1("Pernas Flexoras deitado", 4, "8-10"),
                Exercicio1("Cadeira Flexora", 4, "8-10"),
                Exercicio1("Cadeira Flexora Unilateral", 4, "8-10"),
                Exercicio1("Mesa Flexora", 4, "8-10"),
                Exercicio1("Peso Morto", 4, "8-10"),
                Exercicio1("Flexor deitado", 4, "8-10"),
                Exercicio1("Flexor sentado", 4, "8-10"),
                Exercicio1("Gêmeos em Pé na Máquina", 4, "8-10"),
                Exercicio1("Gêmeos Sentado", 4, "8-10"),
                Exercicio1("Stiff", 4, "8-10"),
                Exercicio1("Leg Curl com Halteres", 4, "8-10"),
                Exercicio1("Curl de Pernas em Máquina", 4, "8-10"),
                Exercicio1("Peso Morto com Barra", 4, "8-10"),
                Exercicio1("Máquina Flexora Unilateral", 4, "8-10"),
                Exercicio1("Máquina Flexora deitado", 4, "8-10"),
                Exercicio1("Leg Curl deitado", 4, "8-10"),
                Exercicio1("Pernas Flexoras deitado", 4, "8-10"),
                Exercicio1("Stiff com Halteres", 4, "8-10"),
                Exercicio1("Curl de Pernas deitado", 4, "8-10"),
                Exercicio1("Prensa 45 graus", 4, "8-10"),
                Exercicio1("Leg Curl em Pé", 4, "8-10"),
                Exercicio1("Curl de Pernas em Máquina Unilateral", 4, "8-10"),
                Exercicio1("Peso Morto com Halteres", 4, "8-10"),
                Exercicio1("Máquina Flexora Sentado", 4, "8-10"),
                Exercicio1("Stiff com Barra Guiada", 4, "8-10"),
                Exercicio1("Curl de Pernas em Máquina Vertical", 4, "8-10"),
                Exercicio1("Curl de Pernas em Máquina Horizontal", 4, "8-10"),
                Exercicio1("Leg Curl em Pé Unilateral", 4, "8-10"),
                Exercicio1("Prensa 45 graus Unilateral", 4, "8-10"),
                Exercicio1("Curl de Pernas em Máquina com Halteres", 4, "8-10"),
                Exercicio1("Leg Curl em Pé com Halteres", 4, "8-10"),
                Exercicio1("Prensa de Pernas Unilateral", 4, "8-10"),
                Exercicio1("Máquina Flexora deitado Unilateral", 4, "8-10"),
                Exercicio1("Prensa de Pernas com Halteres", 4, "8-10"),
                Exercicio1("Leg Curl em Pé com Barra Guiada", 4, "8-10"),
                Exercicio1("Curl de Pernas em Máquina com Barra Guiada", 4, "8-10"),
                Exercicio1("Prensa 45 graus com Halteres", 4, "8-10"),
                Exercicio1("Máquina Flexora Sentado Unilateral", 4, "8-10")
            )
        }

        fun treinoPosteriorCoxaDefinicao(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Leg Curl deitado", 4, "10-12"),
                Exercicio1("Leg Curl em Pé", 4, "10-12"),
                Exercicio1("Peso Morto", 4, "10-12"),
                Exercicio1("Stiff", 4, "10-12"),
                Exercicio1("Prensa de Pernas", 4, "10-12"),
                Exercicio1("Curl de Pernas em Máquina", 4, "10-12"),
                Exercicio1("Leg Curl Unilateral", 4, "10-12"),
                Exercicio1("Prensa 45 graus", 4, "10-12"),
                Exercicio1("Máquina Flexora Sentado", 4, "10-12"),
                Exercicio1("Máquina Flexora deitado", 4, "10-12"),
                Exercicio1("Curl de Pernas em Máquina Unilateral", 4, "10-12"),
                Exercicio1("Prensa de Pernas Unilateral", 4, "10-12"),
                Exercicio1("Máquina Flexora Sentado Unilateral", 4, "10-12"),
                Exercicio1("Máquina Flexora Horizontal", 4, "10-12"),
                Exercicio1("Stiff com Barra Guiada", 4, "10-12"),
                Exercicio1("Curl de Pernas em Máquina com Barra Guiada", 4, "10-12"),
                Exercicio1("Leg Curl em Pé com Barra Guiada", 4, "10-12"),
                Exercicio1("Prensa de Pernas com Halteres", 4, "10-12"),
                Exercicio1("Curl de Pernas em Máquina com Halteres", 4, "10-12"),
                Exercicio1("Prensa de Pernas com Halteres Leves", 4, "10-12"),
                Exercicio1("Leg Curl em Pé com Halteres Leves", 4, "10-12"),
                Exercicio1("Prensa de Pernas Leve", 4, "10-12"),
                Exercicio1("Curl de Pernas em Máquina Leve", 4, "10-12"),
                Exercicio1("Máquina Flexora Sentado Leve", 4, "10-12"),
                Exercicio1("Máquina Flexora deitado Leve", 4, "10-12"),
                Exercicio1("Leg Curl Unilateral Leve", 4, "10-12"),
                Exercicio1("Prensa 45 graus Leve", 4, "10-12"),
                Exercicio1("Stiff Leve", 4, "10-12"),
                Exercicio1("Curl de Pernas em Máquina Unilateral Leve", 4, "10-12"),
                Exercicio1("Prensa de Pernas Unilateral Leve", 4, "10-12"),
                Exercicio1("Máquina Flexora Sentado Unilateral Leve", 4, "10-12"),
                Exercicio1("Máquina Flexora Horizontal Leve", 4, "10-12"),
                Exercicio1("Prensa de Pernas com Halteres Leves", 4, "10-12"),
                Exercicio1("Curl de Pernas em Máquina com Halteres Leves", 4, "10-12"),
                Exercicio1("Prensa de Pernas com Halteres", 4, "10-12"),
                Exercicio1("Curl de Pernas em Máquina com Barra Guiada Leve", 4, "10-12"),
                Exercicio1("Leg Curl em Pé com Barra Guiada Leve", 4, "10-12"),
                Exercicio1("Stiff com Barra Guiada Leve", 4, "10-12")
            )
        }

        fun treinoPosteriorCoxaEmagrecimento(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Corrida", 3, "15-20 minutos"),
                Exercicio1("Caminhada Rápida", 3, "15-20 minutos"),
                Exercicio1("Bicicleta Ergométrica", 3, "15-20 minutos"),
                Exercicio1("Escada", 3, "15-20 minutos"),
                Exercicio1("Natação", 3, "15-20 minutos"),
                Exercicio1("Remo", 3, "15-20 minutos"),
                Exercicio1("Esteira", 3, "15-20 minutos"),
                Exercicio1("Elíptico", 3, "15-20 minutos"),
                Exercicio1("Agachamento com Peso Corporal", 3, "12-15 repetições"),
                Exercicio1("Afundo com Peso Corporal", 3, "12-15 repetições"),
                Exercicio1("Prancha", 3, "30-60 segundos"),
                Exercicio1("Ponte de Glúteos", 3, "12-15 repetições"),
                Exercicio1("Leg Curl deitado", 3, "12-15 repetições"),
                Exercicio1("Stiff com Halteres Leves", 3, "12-15 repetições"),
                Exercicio1("Cadeira Flexora", 3, "12-15 repetições"),
                Exercicio1("Mesa Flexora", 3, "12-15 repetições"),
                Exercicio1("Flexor deitado", 3, "12-15 repetições"),
                Exercicio1("Flexor sentado", 3, "12-15 repetições"),
                Exercicio1("Peso Morto com Barra Leve", 3, "12-15 repetições"),
                Exercicio1("Prensa de Pernas Leve", 3, "12-15 repetições"),
                Exercicio1("Curl de Pernas em Máquina", 3, "12-15 repetições"),
                Exercicio1("Leg Curl em Pé", 3, "12-15 repetições"),
                Exercicio1("Leg Curl em Pé Unilateral", 3, "12-15 repetições"),
                Exercicio1("Prensa 45 graus Leve", 3, "12-15 repetições"),
                Exercicio1("Máquina Flexora Sentado", 3, "12-15 repetições"),
                Exercicio1("Máquina Flexora deitado Unilateral", 3, "12-15 repetições"),
                Exercicio1("Prensa de Pernas com Halteres Leves", 3, "12-15 repetições"),
                Exercicio1("Leg Curl em Pé com Halteres Leves", 3, "12-15 repetições"),
                Exercicio1("Prensa de Pernas com Halteres", 3, "12-15 repetições"),
                Exercicio1("Curl de Pernas em Máquina com Halteres", 3, "12-15 repetições"),
                Exercicio1("Stiff com Barra Guiada Leve", 3, "12-15 repetições"),
                Exercicio1("Curl de Pernas em Máquina com Barra Guiada Leve", 3, "12-15 repetições"),
                Exercicio1("Máquina Flexora Sentado Unilateral", 3, "12-15 repetições"),
                Exercicio1("Máquina Flexora Horizontal Leve", 3, "12-15 repetições")
            )
        }
    }
}

class TreinoGluteos {
    companion object {
        fun treinoGluteosHipertrofia(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Agachamento Sumô", 4, "10-12"),
                Exercicio1("Agachamento Búlgaro", 4, "10-12"),
                Exercicio1("Passada", 4, "10-12"),
                Exercicio1("Stiff", 4, "10-12"),
                Exercicio1("Ponte de Glúteos", 4, "10-12"),
                Exercicio1("Glúteo Kickback com Cabo", 4, "10-12"),
                Exercicio1("Agachamento com Barra", 4, "10-12"),
                Exercicio1("Agachamento com Halteres", 4, "10-12"),
                Exercicio1("Agachamento na Smith Machine", 4, "10-12"),
                Exercicio1("Leg Press", 4, "10-12"),
                Exercicio1("Hip Thrust", 4, "10-12"),
                Exercicio1("Deadlift", 4, "10-12"),
                Exercicio1("Cadeira Abdutora", 4, "10-12"),
                Exercicio1("Cadeira Adutora", 4, "10-12"),
                Exercicio1("Cadeira Extensora", 4, "10-12"),
                Exercicio1("Cadeira Flexora", 4, "10-12"),
                Exercicio1("Glúteo Kickback com Halteres", 4, "10-12"),
                Exercicio1("Afundo com Barra", 4, "10-12"),
                Exercicio1("Agachamento com Bola Suíça", 4, "10-12"),
                Exercicio1("Step Up", 4, "10-12"),
                Exercicio1("Agachamento com Kettlebell", 4, "10-12"),
                Exercicio1("Caminhada com Barra", 4, "10-12"),
                Exercicio1("Caminhada com Halteres", 4, "10-12"),
                Exercicio1("Leg Press com Halteres", 4, "10-12"),
                Exercicio1("Caminhada Lateral com Elástico", 4, "10-12"),
                Exercicio1("Agachamento Pliométrico", 4, "10-12"),
                Exercicio1("Agachamento com Corda", 4, "10-12"),
                Exercicio1("Agachamento com Banda de Resistência", 4, "10-12"),
                Exercicio1("Prensa 45 graus", 4, "10-12"),
                Exercicio1("Cadeira Abdutora Unilateral", 4, "10-12"),
                Exercicio1("Cadeira Adutora Unilateral", 4, "10-12"),
                Exercicio1("Cadeira Extensora Unilateral", 4, "10-12"),
                Exercicio1("Gêmeos em Pé", 4, "10-12"),
                Exercicio1("Gêmeos em Pé com Barra", 4, "10-12"),
                Exercicio1("Peso Morto com Barra", 4, "10-12"),
                Exercicio1("Peso Morto com Halteres", 4, "10-12"),
                Exercicio1("Agachamento na Plataforma Vibratória", 4, "10-12"),
                Exercicio1("Leg Curl em Pé Unilateral", 4, "10-12"),
                Exercicio1("Stiff com Barra Guiada", 4, "10-12"),
                Exercicio1("Agachamento na Smith Machine Unilateral", 4, "10-12")
            )
        }

        fun treinoGluteosEmagrecimento(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Caminhada Rápida", 3, "15-20 minutos"),
                Exercicio1("Corrida", 3, "15-20 minutos"),
                Exercicio1("Escada", 3, "15-20 minutos"),
                Exercicio1("Bicicleta Ergométrica", 3, "15-20 minutos"),
                Exercicio1("Natação", 3, "15-20 minutos"),
                Exercicio1("Remo", 3, "15-20 minutos"),
                Exercicio1("Esteira", 3, "15-20 minutos"),
                Exercicio1("Elíptico", 3, "15-20 minutos"),
                Exercicio1("Agachamento com Peso Corporal", 3, "12-15 repetições"),
                Exercicio1("Afundo com Peso Corporal", 3, "12-15 repetições"),
                Exercicio1("Prancha", 3, "30-60 segundos"),
                Exercicio1("Ponte de Glúteos", 3, "12-15 repetições"),
                Exercicio1("Glúteo Kickback com Elástico", 3, "12-15 repetições"),
                Exercicio1("Agachamento com Bosu", 3, "12-15 repetições"),
                Exercicio1("Step Up com Barra", 3, "12-15 repetições"),
                Exercicio1("Leg Curl deitado", 3, "12-15 repetições"),
                Exercicio1("Stiff com Halteres Leves", 3, "12-15 repetições"),
                Exercicio1("Cadeira Flexora", 3, "12-15 repetições"),
                Exercicio1("Mesa Flexora", 3, "12-15 repetições"),
                Exercicio1("Flexor deitado", 3, "12-15 repetições"),
                Exercicio1("Flexor sentado", 3, "12-15 repetições"),
                Exercicio1("Peso Morto com Barra Leve", 3, "12-15 repetições"),
                Exercicio1("Prensa de Pernas Leve", 3, "12-15 repetições"),
                Exercicio1("Curl de Pernas em Máquina", 3, "12-15 repetições"),
                Exercicio1("Leg Curl em Pé", 3, "12-15 repetições"),
                Exercicio1("Leg Curl em Pé Unilateral", 3, "12-15 repetições"),
                Exercicio1("Prensa 45 graus Leve", 3, "12-15 repetições"),
                Exercicio1("Máquina Flexora Sentado", 3, "12-15 repetições"),
                Exercicio1("Máquina Flexora deitado Unilateral", 3, "12-15 repetições"),
                Exercicio1("Prensa de Pernas com Halteres Leves", 3, "12-15 repetições"),
                Exercicio1("Leg Curl em Pé com Halteres Leves", 3, "12-15 repetições"),
                Exercicio1("Prensa de Pernas com Halteres", 3, "12-15 repetições"),
                Exercicio1("Curl de Pernas em Máquina com Halteres", 3, "12-15 repetições"),
                Exercicio1("Stiff com Barra Guiada Leve", 3, "12-15 repetições"),
                Exercicio1("Curl de Pernas em Máquina com Barra Guiada Leve", 3, "12-15 repetições"),
                Exercicio1("Leg Curl em Pé com Barra Guiada Leve", 3, "12-15 repetições"),
                Exercicio1("Prensa de Pernas com Halteres Leves", 3, "12-15 repetições"),
                Exercicio1("Curl de Pernas em Máquina com Halteres Leves", 3, "12-15 repetições")
            )
        }

        fun treinoGluteosDefinicao(): ArrayList<Exercicio1> {
            return arrayListOf(
                Exercicio1("Agachamento Sumô", 4, "12-15"),
                Exercicio1("Passada", 4, "12-15"),
                Exercicio1("Stiff", 4, "12-15"),
                Exercicio1("Ponte de Glúteos", 4, "12-15"),
                Exercicio1("Glúteo Kickback com Cabo", 4, "12-15"),
                Exercicio1("Agachamento com Barra", 4, "12-15"),
                Exercicio1("Agachamento com Halteres", 4, "12-15"),
                Exercicio1("Agachamento na Smith Machine", 4, "12-15"),
                Exercicio1("Leg Press", 4, "12-15"),
                Exercicio1("Hip Thrust", 4, "12-15"),
                Exercicio1("Deadlift", 4, "12-15"),
                Exercicio1("Cadeira Abdutora", 4, "12-15"),
                Exercicio1("Cadeira Adutora", 4, "12-15"),
                Exercicio1("Cadeira Extensora", 4, "12-15"),
                Exercicio1("Cadeira Flexora", 4, "12-15"),
                Exercicio1("Glúteo Kickback com Halteres", 4, "12-15"),
                Exercicio1("Afundo com Barra", 4, "12-15"),
                Exercicio1("Agachamento com Bola Suíça", 4, "12-15"),
                Exercicio1("Step Up", 4, "12-15"),
                Exercicio1("Agachamento com Kettlebell", 4, "12-15"),
                Exercicio1("Caminhada com Barra", 4, "12-15"),
                Exercicio1("Caminhada com Halteres", 4, "12-15"),
                Exercicio1("Leg Press com Halteres", 4, "12-15"),
                Exercicio1("Caminhada Lateral com Elástico", 4, "12-15"),
                Exercicio1("Agachamento Pliométrico", 4, "12-15"),
                Exercicio1("Agachamento com Corda", 4, "12-15"),
                Exercicio1("Agachamento com Banda de Resistência", 4, "12-15"),
                Exercicio1("Prensa 45 graus", 4, "12-15"),
                Exercicio1("Cadeira Abdutora Unilateral", 4, "12-15"),
                Exercicio1("Cadeira Adutora Unilateral", 4, "12-15"),
                Exercicio1("Cadeira Extensora Unilateral", 4, "12-15"),
                Exercicio1("Gêmeos em Pé", 4, "12-15"),
                Exercicio1("Gêmeos em Pé com Barra", 4, "12-15"),
                Exercicio1("Peso Morto com Barra", 4, "12-15"),
                Exercicio1("Peso Morto com Halteres", 4, "12-15"),
                Exercicio1("Prensa de Pernas", 4, "12-15"),
                Exercicio1("Prensa de Pernas com Halteres", 4, "12-15"),
                Exercicio1("Curl de Pernas em Máquina", 4, "12-15"),
                Exercicio1("Leg Curl em Pé", 4, "12-15")
            )
        }
    }
}

